### ISSUE TITLE
trio-websocket 0.9.0 borks kraken public ws feed

### ISSUE THREAD

**Issue by goodboy** [pikers/piker#127]
Not sure where the problem lies but the error is rooted in `h11`?
Created upstream issue  HyperionGray/trio-websocket#148 

```python
Traceback (most recent call last):
  File "/home/goodboy/repos/piker/3.8/src/tractor/tractor/_actor.py", line 95, in _invoke
    async for item in agen:
  File "/home/goodboy/repos/piker/piker/brokers/kraken.py", line 345, in stream_quotes
    async with trio_websocket.open_websocket_url(
  File "/home/goodboy/repos/piker/3.8/lib/python3.8/site-packages/async_generator/_util.py", line 34, in __aenter__
    return await self._agen.asend(None)
  File "/home/goodboy/repos/piker/3.8/lib/python3.8/site-packages/async_generator/_impl.py", line 366, in step
    return await ANextIter(self._it, start_fn, *args)
  File "/home/goodboy/repos/piker/3.8/lib/python3.8/site-packages/async_generator/_impl.py", line 202, in send
    return self._invoke(self._it.send, value)
  File "/home/goodboy/repos/piker/3.8/lib/python3.8/site-packages/async_generator/_impl.py", line 209, in _invoke
    result = fn(*args)
  File "/home/goodboy/repos/piker/3.8/lib/python3.8/site-packages/trio_websocket/_impl.py", line 124, in open_websocket
    raise DisconnectionTimeout from None
  File "/home/goodboy/repos/piker/3.8/lib/python3.8/site-packages/trio/_core/_run.py", line 815, in __aexit__
    raise combined_error_from_nursery
  File "/home/goodboy/repos/piker/3.8/lib/python3.8/site-packages/trio_websocket/_impl.py", line 1182, in _reader_task
    await self._send(self._initial_request)
  File "/home/goodboy/repos/piker/3.8/lib/python3.8/site-packages/trio_websocket/_impl.py", line 1238, in _send
    data = self._wsproto.send(event)
  File "/home/goodboy/repos/piker/3.8/lib/python3.8/site-packages/wsproto/__init__.py", line 35, in send
    data += self.handshake.send(event)
  File "/home/goodboy/repos/piker/3.8/lib/python3.8/site-packages/wsproto/handshake.py", line 88, in send
    data += self._initiate_connection(event)
  File "/home/goodboy/repos/piker/3.8/lib/python3.8/site-packages/wsproto/handshake.py", line 338, in _initiate_connection
    upgrade = h11.Request(
  File "/home/goodboy/repos/piker/3.8/lib/python3.8/site-packages/h11/_events.py", line 71, in __init__
    self._validate()
  File "/home/goodboy/repos/piker/3.8/lib/python3.8/site-packages/h11/_events.py", line 147, in _validate
    validate(request_target_re, self.target, "Illegal target characters")
  File "/home/goodboy/repos/piker/3.8/lib/python3.8/site-packages/h11/_util.py", line 108, in validate
    raise LocalProtocolError(msg)
h11._util.LocalProtocolError: Illegal target characters
```

Looking at [`trio-websocket` releases](https://github.com/HyperionGray/trio-websocket/releases) it seems it was likely updating to `0.9.0` that introduced this.  Downgrading to `0.8.1` resolves the issue 100%.

Underlying issue seems to be the `h11._events.Request.target` is `b''` and it dies inside `.validate()`?

**Comment by goodboy** [comment]
Solved by [`0.9.1` release](https://github.com/HyperionGray/trio-websocket/releases/tag/0.9.1) :partying_face:.

We prob need a version pin.
