### ISSUE TITLE
Crash when an order is triggered when the notification daemon isn't running (linux only)

### ISSUE THREAD

**Issue by jaredgoldman** [pikers/piker#427]
When performing the following steps, Piker fails:
- Run pikerd with `sudo pikerd --tsdb --pdb`
- Load btc/binance charts with `piker -l cancel --tl -b binance chart --pdb btcusdt.binance`
- Try to place a limit order in paper mode
- Piker fails with the following error
```sh
Traceback (most recent call last):
  File "/home/algorandpa/dev/projects/piker/py-3.10/src/tractor/tractor/_root.py", line 218, in open_root_actor
    yield actor
  File "/home/algorandpa/dev/projects/piker/piker/_daemon.py", line 248, in maybe_open_runtime
    yield
  File "/home/algorandpa/dev/projects/piker/piker/_daemon.py", line 282, in maybe_open_pikerd
    yield portal
  File "/home/algorandpa/dev/projects/piker/piker/ui/_exec.py", line 181, in main
    await func(*((instance,) + args))
  File "/home/algorandpa/dev/projects/piker/piker/ui/_app.py", line 107, in _async_main
    async with (
  File "/home/algorandpa/dev/projects/piker/py-3.10/lib/python3.10/site-packages/trio/_core/_run.py", line 850, in __aexit__
    raise combined_error_from_nursery
  File "/home/algorandpa/dev/projects/piker/piker/ui/_display.py", line 1430, in display_symbol_data
    async with (
  File "/usr/lib/python3.10/contextlib.py", line 217, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/home/algorandpa/dev/projects/piker/piker/ui/order_mode.py", line 677, in open_order_mode
    async with (
  File "/home/algorandpa/dev/projects/piker/py-3.10/lib/python3.10/site-packages/trio/_core/_run.py", line 850, in __aexit__
    raise combined_error_from_nursery
  File "/home/algorandpa/dev/projects/piker/piker/ui/order_mode.py", line 919, in process_trades_and_update_ui
    await process_trade_msg(
  File "/home/algorandpa/dev/projects/piker/piker/ui/order_mode.py", line 1044, in process_trade_msg
    await notify_from_ems_status_msg(msg)
  File "/home/algorandpa/dev/projects/piker/piker/ui/_notify.py", line 86, in notify_from_ems_status_msg
    result = await trio.run_process(
  File "/home/algorandpa/dev/projects/piker/py-3.10/lib/python3.10/site-packages/trio/_subprocess.py", line 740, in run_process
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['notify-send', '-u', 'normal', '-t', '3000', 'piker', "'Struct({'brokerd_msg': None,\n 'cancel_called': False,\n 'name': 'status',\n 'oid': '51534617-bc24-43c3-88b2-5c8b248e58ba',\n 'req': Order(action='alert', exec_mode='live', oid='51534617-bc24-43c3-88b2-5c8b248e58ba', symbol='btcusdt.binance', account='paper', price=17128.25, size=0.0, brokers=['binance']),\n 'reqid': None,\n 'resp': 'triggered',\n 'src': None,\n 'time_ns': 1669859435993422536})'"]' returned non-zero exit status 1.
```

**Comment by goodboy** [comment]
Ok so digging through [`trio.run_process()`](https://github.com/python-trio/trio/blob/master/trio/_subprocess.py#L442) shows that you can pass stdout/err `bool` flags and also avoid the `check: bool = False` error raising.

Further the [`CompletedProcessObject`](https://github.com/python/cpython/blob/0563be23a557917228a8b48cbb31bda285a3a815/Lib/subprocess.py#L126) has all the stdstreams you'l need.
