### ISSUE TITLE
Network failures with daemon in child proc

### ISSUE THREAD

**Issue by tgoodlet** [pikers/piker#43]
I keep noticing a failure when I spawn the broker daemon from an app and the network turns over. From QT anyway, I keep getting the classic:
```   raise BrokerError(resp.body)
 piker.brokers._util.BrokerError: b'{"code":1017,"message":"Access token is invalid"}'
```

Whenever I run the daemon standalone I can't seem to trigger it.

**Comment by tgoodlet** [comment]
Got the same thing after bringing the connection back up moving between APs.

Daemon will be running like so and then crash with:

```python
May 16 13:41:20 (MainThread) [INFO] piker.broker.core core.py:244 New quote ACB.TO:
{('askSize', 129), ('lastTradeSize', 600), ('lastTradeTime', '2018-05-16T13:41:19.962000-04:00'), ('bidSize', 368), ('volume', 13447585), ('VWAP', 7.558898)}
May 16 14:14:39 (MainThread) [WARNING] piker.broker.core core.py:231 Quote query timed out after 3 seconds, retrying...
May 16 14:14:39 (MainThread) [WARNING] piker.broker.core core.py:67 Network is down waiting for re-establishment...
May 16 14:15:07 (MainThread) [WARNING] piker.broker.core core.py:63 Quote query timed out
May 16 14:15:08 (MainThread) [WARNING] piker.broker.core core.py:63 Quote query timed out
May 16 14:15:09 (MainThread) [WARNING] piker.broker.core core.py:63 Quote query timed out
May 16 14:15:10 (MainThread) [WARNING] piker.broker.core core.py:63 Quote query timed out
May 16 14:15:11 (MainThread) [WARNING] piker.broker.core core.py:63 Quote query timed out
May 16 14:15:12 (MainThread) [WARNING] piker.broker.core core.py:63 Quote query timed out
May 16 14:15:13 (MainThread) [WARNING] piker.broker.core core.py:63 Quote query timed out
May 16 14:15:14 (MainThread) [WARNING] piker.broker.core core.py:63 Quote query timed out
May 16 14:15:15 (MainThread) [WARNING] piker.broker.core core.py:63 Quote query timed out
May 16 14:15:16 (MainThread) [WARNING] piker.broker.core core.py:63 Quote query timed out
May 16 14:15:17 (MainThread) [WARNING] piker.broker.core core.py:63 Quote query timed out
May 16 14:15:18 (MainThread) [WARNING] piker.broker.core core.py:63 Quote query timed out
May 16 14:15:19 (MainThread) [WARNING] piker.broker.core core.py:63 Quote query timed out
May 16 14:15:20 (MainThread) [WARNING] piker.broker.core core.py:63 Quote query timed out
May 16 14:15:21 (MainThread) [WARNING] piker.broker.core core.py:63 Quote query timed out
May 16 14:15:22 (MainThread) [WARNING] piker.broker.core core.py:63 Quote query timed out
May 16 14:15:23 (MainThread) [WARNING] piker.broker.core core.py:63 Quote query timed out
May 16 14:15:24 (MainThread) [WARNING] piker.broker.core core.py:63 Quote query timed out
May 16 14:15:25 (MainThread) [WARNING] piker.broker.core core.py:63 Quote query timed out
May 16 14:15:26 (MainThread) [WARNING] piker.broker.core core.py:63 Quote query timed out
May 16 14:15:27 (MainThread) [WARNING] piker.broker.core core.py:63 Quote query timed out
May 16 14:15:28 (MainThread) [WARNING] piker.broker.core core.py:63 Quote query timed out
May 16 14:15:29 (MainThread) [WARNING] piker.broker.core core.py:63 Quote query timed out
Traceback (most recent call last):
  File "/home/tyler/.local/share/virtualenvs/piker-PaB62peT/bin/pikerd", line 11, in <module>
    load_entry_point('piker', 'console_scripts', 'pikerd')()
  File "/home/tyler/.local/share/virtualenvs/piker-PaB62peT/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/tyler/.local/share/virtualenvs/piker-PaB62peT/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/tyler/.local/share/virtualenvs/piker-PaB62peT/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tyler/.local/share/virtualenvs/piker-PaB62peT/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/tyler/repos/piker/piker/cli.py", line 36, in pikerd
    run(partial(_daemon_main, host), loglevel)
  File "/home/tyler/repos/piker/piker/cli.py", line 27, in run
    return trio.run(main)
  File "/home/tyler/.local/share/virtualenvs/piker-PaB62peT/lib/python3.6/site-packages/trio/_core/_run.py", line 1238, in run
    return result.unwrap()
  File "/home/tyler/.local/share/virtualenvs/piker-PaB62peT/lib/python3.6/site-packages/trio/_core/_result.py", line 119, in unwrap
    raise self.error
  File "/home/tyler/.local/share/virtualenvs/piker-PaB62peT/lib/python3.6/site-packages/trio/_core/_run.py", line 1347, in run_impl
    msg = task.context.run(task.coro.send, next_send)
  File "/home/tyler/.local/share/virtualenvs/piker-PaB62peT/lib/python3.6/site-packages/contextvars/__init__.py", line 66, in run
    return callable(*args, **kwargs)
  File "/home/tyler/.local/share/virtualenvs/piker-PaB62peT/lib/python3.6/site-packages/trio/_core/_run.py", line 936, in init
    self.entry_queue.spawn()
  File "/home/tyler/.local/share/virtualenvs/piker-PaB62peT/lib/python3.6/site-packages/async_generator/_util.py", line 42, in __aexit__
    await self._agen.asend(None)
  File "/home/tyler/.local/share/virtualenvs/piker-PaB62peT/lib/python3.6/site-packages/async_generator/_impl.py", line 274, in asend
    return await self._do_it(self._it.send, value)
  File "/home/tyler/.local/share/virtualenvs/piker-PaB62peT/lib/python3.6/site-packages/async_generator/_impl.py", line 290, in _do_it
    return await ANextIter(self._it, start_fn, *args)
  File "/home/tyler/.local/share/virtualenvs/piker-PaB62peT/lib/python3.6/site-packages/async_generator/_impl.py", line 202, in send
    return self._invoke(self._it.send, value)
  File "/home/tyler/.local/share/virtualenvs/piker-PaB62peT/lib/python3.6/site-packages/async_generator/_impl.py", line 209, in _invoke
    result = fn(*args)
  File "/home/tyler/.local/share/virtualenvs/piker-PaB62peT/lib/python3.6/site-packages/trio/_core/_run.py", line 311, in open_nursery
    await nursery._nested_child_finished(nested_child_exc)
  File "/usr/lib64/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/tyler/.local/share/virtualenvs/piker-PaB62peT/lib/python3.6/site-packages/trio/_core/_run.py", line 196, in open_cancel_scope
    yield scope
  File "/home/tyler/.local/share/virtualenvs/piker-PaB62peT/lib/python3.6/site-packages/trio/_core/_multierror.py", line 144, in __exit__
    raise filtered_exc
  File "/home/tyler/.local/share/virtualenvs/piker-PaB62peT/lib/python3.6/site-packages/trio/_core/_run.py", line 196, in open_cancel_scope
    yield scope
  File "/home/tyler/.local/share/virtualenvs/piker-PaB62peT/lib/python3.6/site-packages/trio/_core/_run.py", line 311, in open_nursery
    await nursery._nested_child_finished(nested_child_exc)
  File "/home/tyler/.local/share/virtualenvs/piker-PaB62peT/lib/python3.6/site-packages/trio/_core/_run.py", line 422, in _nested_child_finished
    raise MultiError(self._pending_excs)
  File "/home/tyler/.local/share/virtualenvs/piker-PaB62peT/lib/python3.6/site-packages/trio/_core/_run.py", line 1347, in run_impl
    msg = task.context.run(task.coro.send, next_send)
  File "/home/tyler/.local/share/virtualenvs/piker-PaB62peT/lib/python3.6/site-packages/contextvars/__init__.py", line 66, in run
    return callable(*args, **kwargs)
  File "/home/tyler/repos/piker/piker/brokers/core.py", line 405, in _daemon_main
    log.debug(f"Spawned {listeners}")
  File "/home/tyler/.local/share/virtualenvs/piker-PaB62peT/lib/python3.6/site-packages/async_generator/_util.py", line 42, in __aexit__
    await self._agen.asend(None)
  File "/home/tyler/.local/share/virtualenvs/piker-PaB62peT/lib/python3.6/site-packages/async_generator/_impl.py", line 274, in asend
    return await self._do_it(self._it.send, value)
  File "/home/tyler/.local/share/virtualenvs/piker-PaB62peT/lib/python3.6/site-packages/async_generator/_impl.py", line 290, in _do_it
    return await ANextIter(self._it, start_fn, *args)
  File "/home/tyler/.local/share/virtualenvs/piker-PaB62peT/lib/python3.6/site-packages/async_generator/_impl.py", line 202, in send
    return self._invoke(self._it.send, value)
  File "/home/tyler/.local/share/virtualenvs/piker-PaB62peT/lib/python3.6/site-packages/async_generator/_impl.py", line 209, in _invoke
    result = fn(*args)
  File "/home/tyler/.local/share/virtualenvs/piker-PaB62peT/lib/python3.6/site-packages/trio/_core/_run.py", line 311, in open_nursery
    await nursery._nested_child_finished(nested_child_exc)
  File "/usr/lib64/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/tyler/.local/share/virtualenvs/piker-PaB62peT/lib/python3.6/site-packages/trio/_core/_run.py", line 196, in open_cancel_scope
    yield scope
  File "/home/tyler/.local/share/virtualenvs/piker-PaB62peT/lib/python3.6/site-packages/trio/_core/_multierror.py", line 144, in __exit__
    raise filtered_exc
  File "/home/tyler/.local/share/virtualenvs/piker-PaB62peT/lib/python3.6/site-packages/trio/_core/_run.py", line 196, in open_cancel_scope
    yield scope
  File "/home/tyler/.local/share/virtualenvs/piker-PaB62peT/lib/python3.6/site-packages/trio/_core/_run.py", line 311, in open_nursery
    await nursery._nested_child_finished(nested_child_exc)
  File "/home/tyler/.local/share/virtualenvs/piker-PaB62peT/lib/python3.6/site-packages/trio/_core/_run.py", line 422, in _nested_child_finished
    raise MultiError(self._pending_excs)
  File "/home/tyler/.local/share/virtualenvs/piker-PaB62peT/lib/python3.6/site-packages/trio/_core/_run.py", line 1347, in run_impl
    msg = task.context.run(task.coro.send, next_send)
  File "/home/tyler/.local/share/virtualenvs/piker-PaB62peT/lib/python3.6/site-packages/contextvars/__init__.py", line 66, in run
    return callable(*args, **kwargs)
  File "/home/tyler/repos/piker/piker/brokers/core.py", line 233, in stream_quotes
    quotes = await wait_for_network(partial(get_quotes, tickers))
  File "/home/tyler/repos/piker/piker/brokers/core.py", line 58, in wait_for_network
    quotes = await net_func()
  File "/home/tyler/repos/piker/piker/brokers/questrade.py", line 315, in get_quote
    quotes_resp = await client.api.quotes(ids=ids)
  File "/home/tyler/repos/piker/piker/brokers/questrade.py", line 210, in quotes
    return await self._request('markets/quotes', params={'ids': ids})
  File "/home/tyler/repos/piker/piker/brokers/questrade.py", line 189, in _request
    return resproc(resp, log)
  File "/home/tyler/repos/piker/piker/brokers/_util.py", line 25, in resproc
    raise BrokerError(resp.body)
piker.brokers._util.BrokerError: b'{"code":1017,"message":"Access token is invalid"}'
Exception ignored in: <async_generator object get_client at 0x7fd2a6b735f8>
Traceback (most recent call last):
  File "/home/tyler/repos/piker/piker/brokers/questrade.py", line 284, in get_client
  File "/home/tyler/repos/piker/piker/brokers/questrade.py", line 255, in write_conf
  File "/home/tyler/repos/piker/piker/brokers/config.py", line 34, in write
NameError: name 'open' is not defined
```
I would appear as though some special case handling needs be done per broker. Here with QT the key part is:

```python
File "/home/tyler/repos/piker/piker/brokers/core.py", line 233, in stream_quotes
    quotes = await wait_for_network(partial(get_quotes, tickers))
  File "/home/tyler/repos/piker/piker/brokers/core.py", line 58, in wait_for_network
    quotes = await net_func()
  File "/home/tyler/repos/piker/piker/brokers/questrade.py", line 315, in get_quote
    quotes_resp = await client.api.quotes(ids=ids)
  File "/home/tyler/repos/piker/piker/brokers/questrade.py", line 210, in quotes
    return await self._request('markets/quotes', params={'ids': ids})
  File "/home/tyler/repos/piker/piker/brokers/questrade.py", line 189, in _request
    return resproc(resp, log)
  File "/home/tyler/repos/piker/piker/brokers/_util.py", line 25, in resproc
    raise BrokerError(resp.body)
piker.brokers._util.BrokerError: b'{"code":1017,"message":"Access token is invalid"}'
```
This can be solved by delegating to a `brokermod` defined function which should be called on network failure - that is instead of passing in `get_quotes` to  `wait_for_network()` passing in a `brokermod.on_connection_down()` or something similar.

**Comment by tgoodlet** [comment]
Another issue somewhat related to this is that the `piker.ui.watchlist` client app will bail on reconnect since it will be in the midst of calling `piker.broker._core.Client.aiter_recv()` inside the `update_quotes` task and when the daemon is restarted the task is resumed before the subscription list has been re-established...
