### ISSUE TITLE
`marketstore`: gRPC snappy compression crash?

### ISSUE THREAD

**Issue by goodboy** [pikers/piker#443]
Been seeing this a lot lately on our std tdsb queries:

```python
Jan 13 17:00:40 (brokerd.ib[b5900c], 5413, piker.data.feed.tsdb_backfill.<locals>.back_load_from_tsdb)) [ERROR] piker.data.marketstore marketstore.py:459 Unknown mkts QUERY error: Params(tbk=mnq.cme.20230317.ib/1Sec/OHLCV, start=None, end=2023-01-13T20:04:08+00:00, limit=800000, limit_from_start=None, columns=None)
('RPC failed with status UNKNOWN (2): snappy: corrupt input',)
Traceback (most recent call last):
  File "/home/goodboy/repos/piker/piker/data/marketstore.py", line 456, in read_ohlcv
    result = await client.query(params)
  File "/home/goodboy/.virtualenvs/piker310/src/anyio-marketstore/src/anyio_marketstore/__init__.py", line 168, in query
    reply = await self.stub.Query(reqs)
  File "/home/goodboy/.virtualenvs/piker310/lib/python3.10/site-packages/purerpc/wrappers.py", line 93, in __call__
    return await extract_message_from_singleton_stream(stream)
  File "/home/goodboy/.virtualenvs/piker310/lib/python3.10/site-packages/purerpc/wrappers.py", line 17, in extract_message_from_singleton_stream
    raise_status(event.status)
  File "/home/goodboy/.virtualenvs/piker310/lib/python3.10/site-packages/purerpc/grpclib/exceptions.py", line 120, in raise_status
    raise UnknownError(status.status_message)
purerpc.grpclib.exceptions.UnknownError: RPC failed with status UNKNOWN (2): snappy: corrupt input
```
It unfortunately prevents the prior history from being loaded..

No idea what's up, and we should probably report it upstream, but maybe this is incentive to toy with a new tsdb already 😉

**Comment by goodboy** [comment]
I can't really seem to find anything useful related to this issue and I **don't** think it actually has anything to do with `marketstore`?

For eg. web searching (`"RPC failed with status UNKNOWN (2): snappy: corrupt input"`) yields these mostly unhelpful findings:
- https://github.com/prometheus/prometheus/issues/9474
- https://github.com/Telefonica/prometheus-kafka-adapter/issues/40
  - [ ] @guilledk maybe we can disable compression somehow in `anyio-marketstore` to try and workaround this?
    - https://github.com/grpc/grpc/blob/master/doc/compression.md
    - https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#compressed-flag
    - https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#message-encoding

**Comment by goodboy** [comment]
lul, here's a dump of all the urls i was using before actually just hacking all the repos manually..

- https://github.com/python-trio/purerpc/blob/c490b0eb988b9938210623cbed3b8e6b52c1f5c5/src/purerpc/client.py
- https://github.com/python-trio/purerpc/blob/c490b0eb988b9938210623cbed3b8e6b52c1f5c5/src/purerpc/grpclib/config.py
- https://github.com/python-trio/purerpc/blob/5faa35f2cdf5b36d1398a1aa6a9e681c5344060f/src/purerpc/grpclib/buffers.py#L84
- https://github.com/python-trio/purerpc
